// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wGQNdEnY25VfiXqc2ZGJrZ
// Component: XyDUTZSPLI
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: wGQNdEnY25VfiXqc2ZGJrZ/projectcss
import sty from "./PlasmicTimeDateWidget.module.css"; // plasmic-import: XyDUTZSPLI/css

export type PlasmicTimeDateWidget__VariantMembers = {};

export type PlasmicTimeDateWidget__VariantsArgs = {};
type VariantPropType = keyof PlasmicTimeDateWidget__VariantsArgs;
export const PlasmicTimeDateWidget__VariantProps = new Array<VariantPropType>();

export type PlasmicTimeDateWidget__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicTimeDateWidget__ArgsType;
export const PlasmicTimeDateWidget__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicTimeDateWidget__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultTimeDateWidgetProps {
  children?: React.ReactNode;
  className?: string;
}

export const defaultTimeDateWidget__Args: Partial<PlasmicTimeDateWidget__ArgsType> =
  {};

function PlasmicTimeDateWidget__RenderFunc(props: {
  variants: PlasmicTimeDateWidget__VariantsArgs;
  args: PlasmicTimeDateWidget__ArgsType;
  overrides: PlasmicTimeDateWidget__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultTimeDateWidget__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cufdm
              )}
            >
              {"12:30"}
            </div>
          ),

          value: args.children,
          className: classNames(sty.slotTargetChildren)
        })}
      </div>

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Czwartek, 3 luty 2020"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "text"],
  freeBox: ["freeBox"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTimeDateWidget__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTimeDateWidget__VariantsArgs;
    args?: PlasmicTimeDateWidget__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTimeDateWidget__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTimeDateWidget__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTimeDateWidget__ArgProps,
      internalVariantPropNames: PlasmicTimeDateWidget__VariantProps
    });

    return PlasmicTimeDateWidget__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTimeDateWidget";
  } else {
    func.displayName = `PlasmicTimeDateWidget.${nodeName}`;
  }
  return func;
}

export const PlasmicTimeDateWidget = Object.assign(
  // Top-level PlasmicTimeDateWidget renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicTimeDateWidget
    internalVariantProps: PlasmicTimeDateWidget__VariantProps,
    internalArgProps: PlasmicTimeDateWidget__ArgProps
  }
);

export default PlasmicTimeDateWidget;
/* prettier-ignore-end */
