// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHomeBtn,
  DefaultHomeBtnProps
} from "./plasmic/unicomm_frontend/PlasmicHomeBtn";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface HomeBtnProps extends Omit<DefaultHomeBtnProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultHomeBtnProps altogether and have
// total control over the props for your component.
export interface HomeBtnProps extends DefaultHomeBtnProps {}

function HomeBtn_(props: HomeBtnProps, ref: HTMLElementRefOf<"button">) {
  // Use PlasmicHomeBtn to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHomeBtn are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all HomeBtnProps here, but feel free
  // to do whatever works for you.

  return <PlasmicHomeBtn root={{ ref }} {...props} />;
}

const HomeBtn = React.forwardRef(HomeBtn_);
export default HomeBtn;
