// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wGQNdEnY25VfiXqc2ZGJrZ
// Component: _jlAiRe8-_
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project_mobile_first/plasmic_blank_project_mobile_first.module.css"; // plasmic-import: wGQNdEnY25VfiXqc2ZGJrZ/projectcss
import sty from "./PlasmicMuteIcon.module.css"; // plasmic-import: _jlAiRe8-_/css

import Group8Icon from "./icons/PlasmicIcon__Group8"; // plasmic-import: QjsvoVgKAl/icon

export type PlasmicMuteIcon__VariantMembers = {};

export type PlasmicMuteIcon__VariantsArgs = {};
type VariantPropType = keyof PlasmicMuteIcon__VariantsArgs;
export const PlasmicMuteIcon__VariantProps = new Array<VariantPropType>();

export type PlasmicMuteIcon__ArgsType = {};
type ArgPropType = keyof PlasmicMuteIcon__ArgsType;
export const PlasmicMuteIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicMuteIcon__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultMuteIconProps {
  className?: string;
}

export const defaultMuteIcon__Args: Partial<PlasmicMuteIcon__ArgsType> = {};

function PlasmicMuteIcon__RenderFunc(props: {
  variants: PlasmicMuteIcon__VariantsArgs;
  args: PlasmicMuteIcon__ArgsType;
  overrides: PlasmicMuteIcon__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultMuteIcon__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <Group8Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMuteIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMuteIcon__VariantsArgs;
    args?: PlasmicMuteIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMuteIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMuteIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMuteIcon__ArgProps,
      internalVariantPropNames: PlasmicMuteIcon__VariantProps
    });

    return PlasmicMuteIcon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMuteIcon";
  } else {
    func.displayName = `PlasmicMuteIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicMuteIcon = Object.assign(
  // Top-level PlasmicMuteIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicMuteIcon
    internalVariantProps: PlasmicMuteIcon__VariantProps,
    internalArgProps: PlasmicMuteIcon__ArgProps
  }
);

export default PlasmicMuteIcon;
/* prettier-ignore-end */
