// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wGQNdEnY25VfiXqc2ZGJrZ
// Component: PKQxjs1wgm
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project_mobile_first/plasmic_blank_project_mobile_first.module.css"; // plasmic-import: wGQNdEnY25VfiXqc2ZGJrZ/projectcss
import sty from "./PlasmicDateTimeWidget.module.css"; // plasmic-import: PKQxjs1wgm/css

export type PlasmicDateTimeWidget__VariantMembers = {};

export type PlasmicDateTimeWidget__VariantsArgs = {};
type VariantPropType = keyof PlasmicDateTimeWidget__VariantsArgs;
export const PlasmicDateTimeWidget__VariantProps = new Array<VariantPropType>();

export type PlasmicDateTimeWidget__ArgsType = {
  timeText?: React.ReactNode;
  dateText?: React.ReactNode;
};

type ArgPropType = keyof PlasmicDateTimeWidget__ArgsType;
export const PlasmicDateTimeWidget__ArgProps = new Array<ArgPropType>(
  "timeText",
  "dateText"
);

export type PlasmicDateTimeWidget__OverridesType = {
  root?: p.Flex<"div">;
  frame4010?: p.Flex<"div">;
};

export interface DefaultDateTimeWidgetProps {
  timeText?: React.ReactNode;
  dateText?: React.ReactNode;
  className?: string;
}

function PlasmicDateTimeWidget__RenderFunc(props: {
  variants: PlasmicDateTimeWidget__VariantsArgs;
  args: PlasmicDateTimeWidget__ArgsType;
  overrides: PlasmicDateTimeWidget__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"frame4010"}
        data-plasmic-override={overrides.frame4010}
        className={classNames(projectcss.all, sty.frame4010)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__gvgzt)}>
          {p.renderPlasmicSlot({
            defaultContents: "Poniedziałek\n30 październik 2022",
            value: args.dateText,
            className: classNames(sty.slotTargetDateText)
          })}
        </div>

        <div className={classNames(projectcss.all, sty.freeBox__nhfSo)}>
          {p.renderPlasmicSlot({
            defaultContents: "14:22",
            value: args.timeText,
            className: classNames(sty.slotTargetTimeText)
          })}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "frame4010"],
  frame4010: ["frame4010"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  frame4010: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDateTimeWidget__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDateTimeWidget__VariantsArgs;
    args?: PlasmicDateTimeWidget__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDateTimeWidget__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicDateTimeWidget__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDateTimeWidget__ArgProps,
          internalVariantPropNames: PlasmicDateTimeWidget__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicDateTimeWidget__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDateTimeWidget";
  } else {
    func.displayName = `PlasmicDateTimeWidget.${nodeName}`;
  }
  return func;
}

export const PlasmicDateTimeWidget = Object.assign(
  // Top-level PlasmicDateTimeWidget renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    frame4010: makeNodeComponent("frame4010"),

    // Metadata about props expected for PlasmicDateTimeWidget
    internalVariantProps: PlasmicDateTimeWidget__VariantProps,
    internalArgProps: PlasmicDateTimeWidget__ArgProps
  }
);

export default PlasmicDateTimeWidget;
/* prettier-ignore-end */
